# Generated by Django 6.0.5 on 2026-05-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_movies_movi_title_652549_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(default=2024),
        ),
    ]
