# Generated by Django 6.0.5 on 2026-05-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='banner_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
