# Generated by Django 6.0.5 on 2026-05-22 15:46

import movies.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, storage=movies.storage.VideoMediaCloudinaryStorage(), upload_to='videos/'),
        ),
    ]
